[project]
name = "architecture-pro-quantum-forge"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "sentence-transformers>=5.1.1",
    "torch<=2.7.1",
    "transformers>=4.56.2",
]
